apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: style-guide-common
  name: style-guide-common
spec:
  ports:
  - name: "5000"
    port: 5000
    nodePort: 30001
    protocol: TCP
    targetPort: 5000
  selector:
    io.kompose.service: style-guide-common
  type: NodePort