language: node_js

node_js:
  - '12.15'

env:
  global:
  - TIMESTAMP=$(date +%y%m%d%H%M)
  - DOCKER_USERNAME="irfanandriansyah1997"

services:
  - docker

script:
  - make init-test
  - make build-asset

deploy:
  - provider: npm
    email: irfanandriansyah10@gmail.com
    skip_cleanup: true
    api_key: ab599ead0892e12772e70ac2f3b2543a28bdeffc
    on:
      branch: master
      repo: urbanindo/style-guide
  - provider: script
    skip_cleanup: true
    script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make build-docker version=${TIMESTAMP}
    on:
        branch: master