language: python

python:
  - "3.6"

node_js:
  - '12.15'

git:
  submodules: false

env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAYD73MS25G7K74AHI
  - TIMESTAMP=$(date +%y%m%d%H%M)
  - AWS_REGION=ap-southeast-1
  - BRANCH_NAME=$TRAVIS_BRANCH
  - APP_NAME=thesis-design-system
  - DOCKER_USERNAME="irfanandriansyah1997"

install: skip

services:
  - docker

before_script:
  - nvm ls-remote
  - nvm install 12.5
  - yarn install
  - npm rebuild node-sass
  - node -v

script:
  - node -v
  - make init-test
  - bash <(curl -s https://codecov.io/bash) -t 8de315f6-6f4a-4eea-a24a-d3e42af54287
  - make build-javascript

before_deploy:
  - make build-documentation

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy version=${TIMESTAMP} name=${APP_NAME} username=${DOCKER_USERNAME} password=${DOCKER_PASSWORD}
    on:
        branch: master
  - provider: npm
    email: irfanandriansyah10@gmail.com
    skip_cleanup: true
    api_key: ab599ead0892e12772e70ac2f3b2543a28bdeffc
    on:
      branch: master
      repo: irfanandriansyah1997/thesis