language: node_js

node_js:
  - '12.15'

env:
  global:
  - TIMESTAMP=$(date +%y%m%d%H%M)
  - DOCKER_USERNAME="irfanandriansyah1997"

services:
  - docker

script:
  - make init-test
  - make build-asset

# before_deploy:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - make build-docker-image version=${TIMESTAMP}

deploy:
  - provider: script
    skip_cleanup: true
    script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make build-docker-image version=${TIMESTAMP}
    on:
        branch: master
