language: node_js
node_js:
  - '12.15'

script:
  - yarn run check-code
  - yarn run build-asset
  - yarn run build-documentation
  - ./node_modules/.bin/codecov --token=b4765ae3-4fd3-4af9-89e5-b44876a1764b

deploy:
  - provider: npm
    email: irfanandriansyah10@gmail.com
    skip_cleanup: true
    api_key: e97ededd-8242-4e57-ac03-9884c448bb0b
    on:
      branch: master
      repo: urbanindo/style-guide
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: documentation
    on:
      branch: master
