language: node_js
node_js:
  - '12.15'

script:
  - yarn run check-code
  - yarn run build-asset
  - yarn run build-documentation
  - ./node_modules/.bin/codecov --token=b4765ae3-4fd3-4af9-89e5-b44876a1764b

deploy:
  - provider: npm
    email: irfanandriansyah10@gmail.com
    skip_cleanup: true
    api_key:
        secure: Sw1N+Ig0cXNo5j5YFBW8JwXQYqm3i6Fj8LDorD/AZ419KWgrTk1SevTyTSBuR2gLqCIpUf/vlwlnIoAtQXx0DLWYFVfCMh+gR6zTaMN9r9/Nn3pz+/pSi87s/MNFMjhLW/vp1C/Gag6exmzbMGGOB0A82g7G8+CI4o4wh3O3JDIenzdC4D6aNkFQS4YX2UJP/6DTM61KFMjEyc9P9wAftSMp+0HsVYsurUkM6PAHHkNDCqmVmWAoSeNLKzBq5NoY51AHEOuZFzVXnxxw9QGi0uMrU+wvfXgafK4kS/I/hJKnerFJ0PsznN9hdQPJeZGx2B0E8iSgBAsneKBHvZnlpEpTP+frjF1A0UMu5/hDGNDTcIVt4VI9Eh+oG0DkdoRniMjBmnSzK3xpsPcG9hzZzgpjN24m9zvYbd+LTQ7bH+rLTegvAHDOKwp4jD08bZWl8iYAxrPkPPRolz36sc7qT0qRRc9lT801A+RgiYhsg/rPycTo4/NGqDSxmpPnMz47gUWHg2EyR7x2qn2gQfhdzMJlG7NzKOgzfUPJ3dvDG5JaJodONvUZ3Gg7hSGovqX/CMAKXTe75CnnOMDp5HCPuFrc6MJCzr+nERjG5h7Fxf9kavEvZpvOR0K0tsCWNZH1i4tOg25x7DX/FOHB43KaV4yHHbksWlGJ8X+UaHhIDjg=
    on:
      branch: master
      repo: irfanandriansyah1997/base-component
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: documentation
    on:
      branch: master
