#####################################################################
# Codecov configuration.
#####################################################################
ignore:
    - "**/etc/.*"
    - "**/*.svg"
    - "**/*.scss"
    - "**/types/.*"
    - "**/*.spec.ts"
    - "**/*.spec.tsx"
    - "**/__mocks__/.*"
    - "**/*.stories.ts"
    - "**/*.stories.tsx"
    - "**/interfaces/.*"
    - "src/documentation/.*"
    - "**/*.documentation.ts"
    - "**/*.documentation.tsx"
    - "src/documentation/app.tsx"