###########################################################################
## Docker Base File For Build Styleguide
## @author: Irfan Andriansyah <irfanandriansyah10@gmail.com>
## @since: 2020.03.23
###########################################################################

FROM node:12.16.1-alpine

# Create app directory
RUN mkdir -p /usr/src/thesis
WORKDIR /usr/src/thesis