apiVersion: v1
kind: Service
metadata:
  annotations:
    label: 99 frontend styleguide
  creationTimestamp: null
  name: style-guide-desktop-site
spec:
  type: LoadBalancer
status:
  loadBalancer: {}